# Generated by Django 6.0.3 on 2026-03-09 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DomainWatchItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base_name", models.CharField(max_length=63)),
                ("tlds", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("last_statuses", models.JSONField(default=dict)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="domainamer__is_acti_39f21e_idx"
                    ),
                    models.Index(
                        fields=["updated_at"], name="domainamer__updated_5777ac_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DomainAlertEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(max_length=255)),
                ("previous_status", models.CharField(max_length=32)),
                ("current_status", models.CharField(max_length=32)),
                ("checked_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "watch_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="domainamer.domainwatchitem",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["domain", "created_at"],
                        name="domainamer__domain_2ba59f_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="domainamer__created_192af9_idx"
                    ),
                ],
            },
        ),
    ]
