# Generated by Django 6.0.3 on 2026-03-10 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domainamer", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WatchlistCheckJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("summary", models.JSONField(default=dict)),
                ("error_message", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="domainwatchitem",
            name="canonical_tlds",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="domainwatchitem",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="domain_watch_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="domainwatchitem",
            index=models.Index(
                fields=["owner", "is_active"], name="domainamer__owner_i_045295_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="domainwatchitem",
            constraint=models.UniqueConstraint(
                fields=("owner", "base_name", "canonical_tlds"),
                name="uq_watch_owner_base_tlds",
            ),
        ),
        migrations.AddField(
            model_name="watchlistcheckjob",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="watchlist_check_jobs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="watchlistcheckjob",
            index=models.Index(
                fields=["owner", "status"], name="domainamer__owner_i_83f95f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="watchlistcheckjob",
            index=models.Index(
                fields=["created_at"], name="domainamer__created_8420ad_idx"
            ),
        ),
    ]
