"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9f047uav+r=0gq)*gro@^%4f_4bb&0l!h1m!#-s5pr^t9^59=9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'domainamer',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Domain availability hardening configuration
DOMAIN_HARDENED_CHECK_ENABLED = True
DOMAIN_HARDENED_FALLBACK_TO_LEGACY = True
DOMAIN_SHADOW_MODE = False
DOMAIN_REAL_PROVIDER_ENABLED = False
DOMAIN_RDAP_ENDPOINT_TEMPLATE = "https://rdap.org/domain/{domain}"
DOMAIN_WHOIS_SERVER = "whois.verisign-grs.com"

AVAILABILITY_PROVIDER_TIMEOUT_MS = 1200
AVAILABILITY_BUDGET_TIMEOUT_MS = 1800
AVAILABILITY_QUORUM_MIN = 2
AVAILABILITY_UNCERTAIN_CONFIDENCE_CAP = 0.49
AVAILABILITY_MAX_ATTEMPTS_PER_PROVIDER = 3

IP_POOL_COOLDOWN_BASE_SEC = 60
IP_POOL_COOLDOWN_MAX_SEC = 600
DOMAIN_CHECK_IP_POOL = ["10.0.0.1", "10.0.0.2", "10.0.0.3"]

CONFIDENCE_WEIGHT_AGREEMENT = 0.45
CONFIDENCE_WEIGHT_SOURCE = 0.20
CONFIDENCE_WEIGHT_HEALTH = 0.15
CONFIDENCE_WEIGHT_FRESHNESS = 0.10
CONFIDENCE_WEIGHT_ERROR = 0.10

# Demo provider behavior controls (replace with real provider adapters in production).
DOMAIN_UNAVAILABLE_DOMAINS = ["brandhub.com", "takenbrand.com"]
DOMAIN_TIMEOUT_DOMAINS = []
DOMAIN_RATE_LIMITED_DOMAINS = []

# Rollout and alert references
DOMAIN_ROLLOUT_PLAYBOOK = ["shadow", "canary_10", "canary_50", "full_100"]
ALERT_UNCERTAIN_RATE_WARNING = 0.07
ALERT_FALSE_AVAILABLE_RATE_CRITICAL = 0.003
